# -*- coding: utf-8 -*-
"""Built-ins

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xwlCUs37anw-LGpJUFYSYh18gRwP_XC0
"""

idades = [15, 87, 32, 65, 56, 32, 49, 37]

for idade in idades:
    print(idade)    # imprime os valores da lista idades

idades = [15, 87, 32, 65, 56, 32, 49, 37]

len(idades)  # retorna o comprimento da lista

idades = [15, 87, 32, 65, 56, 32, 49, 37]

range(len(idades))  # retorna o primeiro valor da lista e seu comprimento

idades = [15, 87, 32, 65, 56, 32, 49, 37]

for i in range(len(idades)):
    print(i)    # retorna as posições dos valores na lista

idades = [15, 87, 32, 65, 56, 32, 49, 37]

for i in range(len(idades)):
    print(i, idades[i])  # retorna posição e valores da lista

enumerate(idades)  # guarda as duplas de posição + valor

list(range(len(idades)))  # força a geração dos valores

list(enumerate(idades))  # gera posição e valores dentro da lista de tuplas

for valor in enumerate(idades):
    print(valor)    # gera as duplas de valores em tuplas

for indice, idade in enumerate(idades):
    print(indice, "x", idade)   # desempacotando as tuplas

usuarios = [
    ("Andrea", 35, 1987),
    ("Neuza", 63, 1959),
    ("Eloisa", 9, 2013),
]

for usuario in usuarios:
    print(usuario)

usuarios = [
    ("Andrea", 35, 1987),
    ("Neuza", 63, 1959),
    ("Eloisa", 9, 2013),
]

for nome, idade, nascimento in usuarios:
    print(nome)  # desempacotando um item das tuplas

for nome, _, _ in usuarios:  # ignorando os elementos que não se quer gerar
    print(nome)
