# -*- coding: utf-8 -*-
"""Ordenação básica

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18i7cWnydLVXDTGkz8FMm97u9r-lXfOw7
"""

idades = [15, 87, 32, 65, 56, 32, 49, 37]
idades

sorted(idades)

15 < 32

list(reversed(idades))

sorted(idades, reverse=True)

idades

idades.sort(reverse=True)
idades
